spring.application.name=gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=produtos-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://produtos-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/produtos/**

spring.cloud.gateway.server.webflux.routes[2].id=clientes-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://clientes-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/clientes/**

spring.cloud.gateway.server.webflux.routes[3].id=vendas-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://vendas-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/vendas/**

server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=00d23b30-8bd5-4cfa-935c-9305be24d5f7
